name: adguard-home
services:
  adguardhome:
    image: adguard/adguardhome:v0.107.71@sha256:92929135ced2554aaf94706f766a98ad348f211df61b0704e2db7e8498cc00b7
    restart: unless-stopped
    container_name: adguardhome
    networks:
      - proxy
    ports:
      - 53:53/tcp
      - 53:53/udp
    #   - 880:80/tcp
    #   - 3001:3000/tcp
    volumes:
      - /etc/adguardhome/workdir:/opt/adguardhome/work
      - /etc/adguardhome/confdir:/opt/adguardhome/conf
    labels:
      - traefik.enable=true
      - traefik.http.services.adguard-home.loadbalancer.server.port=3000

networks:
  proxy:
    external: true
