name: adguard-home
services:
  adguardhome:
    image: adguard/adguardhome:v0.107.70@sha256:33e2240c466b2bb1d4fe9d65fd86178160bf6ee8835cf7b50ab3a7c5e39571fe
    restart: unless-stopped
    container_name: adguardhome
    networks:
      - proxy
    ports:
      - 53:53/tcp
      - 53:53/udp
    #   - 880:80/tcp
    #   - 3001:3000/tcp
    volumes:
      - /etc/adguardhome/workdir:/opt/adguardhome/work
      - /etc/adguardhome/confdir:/opt/adguardhome/conf
    labels:
      - traefik.enable=true
      - traefik.http.services.adguard-home.loadbalancer.server.port=3000

networks:
  proxy:
    external: true
