services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:13@sha256:88858e7f592f82d4f650713c7bed8c0cd792d7f71475a7467c5650a31cd2eda9
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /etc/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.forgejo.loadbalancer.server.port=3000

      - traefik.tcp.routers.forgejo-ssh.entrypoints=ssh
      - traefik.tcp.routers.forgejo-ssh.rule=HostSNI(`*`)
      - traefik.tcp.routers.forgejo-ssh.service=forgejo-ssh
      - traefik.tcp.services.forgejo-ssh.loadbalancer.server.port=2222

networks:
  proxy:
    external: true
