services:
  nc:
    image: nextcloud:stable-apache
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - nc_data:/var/www/html
    networks:
      - redisnet
      - dbnet
      - proxy
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - TRUSTED_PROXIES=192.168.20.50 100.64.0.15
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nextcloud.simenmo.com

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - redisnet
    expose:
      - 6379

  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dbnet
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
    expose:
      - 3306

volumes:
  db_data:
  nc_data:
networks:
  dbnet:
  redisnet:
