global:
  sendAnonymousUsage: false
log:
  level: WARN
api:
  dashboard: false
  insecure: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      tls:
        certResolver: hetzner

  ssh:
    address: ":2222/tcp"

providers:
  file:
    directory: /etc/traefik/dynamic/
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    defaultRule: 'Host(`{{ index .Labels "com.docker.compose.service"}}.simenmo.com`)'
    network: proxy
certificatesResolvers:
  hetzner:
    acme:
      email: "simenmunch@gmail.com"
      storage: "/var/traefik/certs/acme.json"
      dnsChallenge:
        provider: hetzner
        resolvers:
          - 213.133.100.98
          - 88.198.229.192
          - 193.47.99.5
tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: hetzner
        domain:
          main: "simenmo.com"
          sans: "*.simenmo.com"
