services:
  woodpecker:
    image: woodpeckerci/woodpecker-server:v3.12.0
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=https://woodpecker.simenmo.com
      - WOODPECKER_FORGEJO=true
      - WOODPECKER_FORGEJO_URL=https://forgejo.simenmo.com
      - WOODPECKER_FORGEJO_CLIENT=${WOODPECKER_FORGEJO_CLIENT}
      - WOODPECKER_FORGEJO_SECRET=${WOODPECKER_FORGEJO_SECRET}
      - WOODPECKER_PLUGINS_PRIVILEGED=woodpeckerci/plugin-docker-buildx
      - WOODPECKER_PLUGINS_TRUSTED_CLONE=docker.io/woodpeckerci/plugin-git,docker.io/woodpeckerci/plugin-git,quay.io/woodpeckerci/plugin-git,ghcr.io/simen64/gitverify-clone
      - WOODPECKER_ADMIN=simen64
      # - AGENT_SECRET=${AGENT_SECRET}
    networks:
      - woodpecker
      - proxy
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.woodpecker-service.loadbalancer.server.port=8000

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3.11.0
    command: agent
    restart: always
    networks:
      - woodpecker
    depends_on:
      - woodpecker
    volumes:
      - woodpecker-agent-config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker:9000
      - WOODPECKER_AGENT_SECRET=${AGENT_SECRET}
      - WOODPECKER_HEALTHCHECK_ADDR=:3002

volumes:
  woodpecker-server-data:
  woodpecker-agent-config:

networks:
  woodpecker:
  proxy:
    external: true
